### ISSUE TITLE
ripples to the past

### ISSUE THREAD

**Issue by Thetardisowner** [Gallifrey-Craft/Gallifreycraft#6]
a mod i think is good fun that adds several features based of the anime jojos bizarre adventures.
it contains the ability to summon stands and use them for fighting and other abilitys such as instant repairing broken blocks and stopping time in a area, and the ability to use the mysterious force known as hamon.
and another ability to turn into a vampire which removes the need for food and makes most hostile mobs no longer agressive but your unable to enter the sunlight. 

along with this mod that adds several stands and abilitys it also adds 3 new locations such as the meteriorite, hamon temple and the piller men temple.

Aswell the discord for the mod has several players that have made their own addons that add even more stand to the count of about 23 new stands that are constantly updated and tweaked to be survival friendly and stop it from being OP

and if wanted the server can have a arena to have battles dedicated to stand fights and events

if u wish to discuss the mod more extensivly please msg me

p.s if u do agree to add the mod add the modrinth version as thats the latest version of the base mod

**Comment by Batman2741** [comment]
define what you mean by "stands" also give more detail on the time stop and vampire abilities

**Comment by Thetardisowner** [comment]
stands are a ghost like being that represents the soul of the user, they have a myriad of designs from humanoid to objects
they have the ability to fight with different  moves and combos they are obtained by using something called a stand arrow (or beetle arrow) where if ur lvl 30 u stab urself and ur health drains but as long as u have the required lvls of xp u shouldnt die from it.
as for vampirism, it grants multitude of abilitys such as
1. blood drain. the ability to feed Ur self as when ur a vampire u no longer need air or food
u can drain blood from passive mobs but things like illigers and villagers and players give most amount of blood to feed urself.
with full blood ur granted strength speed and health regen
2. zombie summon, lets u summon ur own zombies that will attack anything u instruct them to by punching the entity u want them to fight, while draining from a pilliger or villiger they have a chance to turn into a zombie.
3. lazer eyes, a massive high hitting attack where u shoot lazers from ur eyes but its also very destructive to the enviroment, note it does drain a quater of ur blood.
4. freeze touch, the ability to freeze a player or mob in their place while it does plenty of damage.
To obtain vamperism u must find the piller man temple (found in jungles) and take one of the masks found on a statue in the basement, then u must wear it and attack mobs where after a couple hit the mask will activate and turn u into a vampire.
thats the abilitys that come to mind for vamperism so ill move to time stop
Time Stop: the ability to freeze time in a radius of about 32 blocks with a limit of 5 seconds maxed but u must train ur timestop by using it,
there are only 2 stands that have timestop
"star platnium" and "the world"
both have this ability plus others but timestop is a usefull tool both have.
but "the world" is the only stand where timestop can be upgraded
to upgrade it u must have vamperism (as the owner of the stand from jojo's bizarre adventure is a vampire)
it can be upgraded to 9 seconds of time stop with training and vamperism
(small note on the stands, non stand users aka players without a stand cannot see other players stands, only stand users can see other players stands)

**Comment by Batman2741** [comment]
ima say maybe for now
