### ISSUE TITLE
some mods u could add

### ISSUE THREAD

**Issue by ToastMan5** [Gallifrey-Craft/Gallifreycraft#8]
Sophisticated Backpacks ............................ (Just backpacks)
Minecraft Transit Railway................................. (Helps find bioms and structures, speperate mods)
infinite trading..................................................... (No out of stock on villagers)
target dummy ................................................... (Dummy shows damage output of weapon)
stalwart dungeons...........................................(Tons of new structures that are noice)
when dungeons arrise........................................ (Tons of new structures that are kinda vannilla +)
twilight forest.................................................... (Dont need an explanation)
tropicraft................................................................. (nice tropical dimention works well with tardis)
bumlezone.......................................................(Bee dimention)
enchanting infuser.......................................... (allows u to choose enchantments    (configurable so unique ones cost way more)    )
unique enchants....(All varients?) ................(Bunch more usefull enchants)
toasty discs                                            (My mod adds a bunch of music discs)

**Comment by Batman2741** [comment]
editing list for possibles in your post
Sophisticated Backpacks ............................ (Just backpacks)
Sophisticated Backpacks ............................ (Just backpacks)
when dungeons arrise........................................ (Tons of new structures that are kinda vannilla +)
twilight forest.................................................... (Dont need an explanation)
tropicraft................................................................. (nice tropical dimention works well with tardis)
